version: 2.1
default: &default
  working_directory: ~/repo
  docker:
    - image: circleci/node:14
commands:
  prepare:
    description: "Prepare working directory"
    steps:
      # update to latest npm to support lock file version 2
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run:
          name: Update NPM
          command: |
            echo "prefix=~/.npm-global" > ~/.npmrc
            npm i -g npm
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
jobs:
  build:
    <<: *default
    steps:
      - prepare
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
  deploy:
    <<: *default
    steps:
      - prepare
      - run:
          name: Bump version
          command: |
            git config user.email circleci@circleci
            git config user.name CircleCI
            git checkout -- package-lock.json
            npm version patch -m "patch version bump %s [ci skip]"
            git push --set-upstream origin master-0.0
            git push --tags
      - run:
          name: Publish
          command: |
            git status
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            npm publish --access public
workflows:
  version: 2.1
  build-flow:
    jobs:
      - build:
          filters:
            branches:
              ignore: master-0.0
      - deploy:
          filters:
            branches:
              only: master-0.0
